// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");

function cmp(x1, x2) {
  var y = Caml_obj.compare(x1, x2);
  console.log(y);
  return y;
}

var z1 = cmp(1, 1);

var z2 = cmp(1, 0);

var z3 = cmp(0, 1);

var a1 = cmp(0.1, 1.1);

exports.cmp = cmp;
exports.z1 = z1;
exports.z2 = z2;
exports.z3 = z3;
exports.a1 = a1;
/* z1 Not a pure module */
