// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Http = require("http");
var RescriptReactRouter = require("@rescript/react/src/RescriptReactRouter.bs.js");

var contentType = {
  "Content-Type": "text/html"
};

var server = Http.createServer(function (request, response) {
      var url = RescriptReactRouter.useUrl(undefined, undefined);
      console.log("Request:");
      console.log(url);
      console.log(request.url);
      console.log(request.method);
      response.writeHead(200, contentType);
      response.end("This is a failed attempt to return a React component!");
    });

server.listen(3000, (function (param) {
        console.log("server is running on 3000");
      }));

exports.contentType = contentType;
exports.server = server;
/* server Not a pure module */
