// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function ReactComponent(Props) {
  return React.createElement("div", undefined, "Hello World");
}

var make = ReactComponent;

exports.make = make;
/* react Not a pure module */
